Watching for file changes with StatReloader
Not Found: /docs
"GET /docs HTTP/1.1" 404 2424
Index page accessed
Internal Server Error: /main/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 15, in main
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/main.html
"GET /main/ HTTP/1.1" 500 79719
Index page accessed
Internal Server Error: /main/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 15, in main
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/main.html
"GET /main/ HTTP/1.1" 500 79856
Index page accessed
Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 21, in about
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/about.html
"GET /about/ HTTP/1.1" 500 78871
Index page accessed
Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 21, in about
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/about.html
"GET /about/ HTTP/1.1" 500 78597
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2394
Index page accessed
Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 21, in about
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/about.html
"GET /about/ HTTP/1.1" 500 78871
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4158
"GET /static/admin/css/base.css HTTP/1.1" 200 21544
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
"GET /static/admin/css/login.css HTTP/1.1" 200 958
"GET /static/admin/css/responsive.css HTTP/1.1" 200 17905
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2682
"GET /static/admin/js/theme.js HTTP/1.1" 200 1943
Index page accessed
Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 21, in about
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/about.html
"GET /about/ HTTP/1.1" 500 79472
Index page accessed
Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 21, in about
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/about.html
"GET /about/ HTTP/1.1" 500 79198
Index page accessed
Internal Server Error: /main/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 15, in main
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/main.html
"GET /main/ HTTP/1.1" 500 80594
Index page accessed
Internal Server Error: /main/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 15, in main
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/main.html
"GET /main/ HTTP/1.1" 500 80320
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2394
Not Found: /docs
"GET /docs HTTP/1.1" 404 2424
Index page accessed
"GET /main/ HTTP/1.1" 200 183
Index page accessed
"GET /main/ HTTP/1.1" 200 183
Index page accessed
"GET /about/ HTTP/1.1" 200 176
Index page accessed
"GET /about/ HTTP/1.1" 200 176
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2394
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hwproject\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /hw2
"GET /hw2 HTTP/1.1" 404 2525
Internal Server Error: /hw2/customer_ordered_products/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py", line 18, in customer_ordered_products
    return render(request, 'orders/customer_ordered_products.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: orders/customer_ordered_products.html
"GET /hw2/customer_ordered_products/ HTTP/1.1" 500 89802
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hw2/customer_ordered_products/ HTTP/1.1" 200 9282
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hw2/customer_ordered_products/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2112, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Alex'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py", line 9, in customer_ordered_products
    orders_last_7_days = OrderModel.objects.filter(customer_id=client_id, date_order__gte=timezone.now() - timedelta(days=7))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1602, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1634, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1548, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1378, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2114, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'Alex'.
"GET /hw2/customer_ordered_products/ HTTP/1.1" 500 128206
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hw2/customer_ordered_products/ HTTP/1.1" 200 6135
"GET /hw2/customer_ordered_products/ HTTP/1.1" 200 6135
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hw2/customer_ordered_products/ HTTP/1.1" 200 2277
"GET /hw2/customer_ordered_products/ HTTP/1.1" 200 2277
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hw2/customer_ordered_products/ HTTP/1.1" 200 828
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /hw2/history_of_orders/ HTTP/1.1" 200 828
"GET /hw2/history_of_orders/ HTTP/1.1" 200 828
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hw2/history_of_orders/ HTTP/1.1" 200 1248
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hw2/history_of_orders/ HTTP/1.1" 200 2277
Watching for file changes with StatReloader
"GET /hw2/history_of_orders/ HTTP/1.1" 200 2277
Not Found: /hw2/history_of_orders/1
"GET /hw2/history_of_orders/1 HTTP/1.1" 404 2676
Not Found: /hw2/history_of_orders/2
"GET /hw2/history_of_orders/2 HTTP/1.1" 404 2676
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2498
Not Found: /hw2/history_of_orders/1
"GET /hw2/history_of_orders/1 HTTP/1.1" 404 2676
"GET /hw2/history_of_orders/ HTTP/1.1" 200 2277
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2498
Not Found: /prefix/
"GET /prefix/ HTTP/1.1" 404 2537
Not Found: /products/
"GET /products/ HTTP/1.1" 404 2543
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /products/
"GET /products/ HTTP/1.1" 404 2543
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2498
Not Found: /prefix/
"GET /prefix/ HTTP/1.1" 404 2537
Not Found: /products/
"GET /products/ HTTP/1.1" 404 2543
Not Found: /products_form/
"GET /products_form/ HTTP/1.1" 404 2558
"GET /hw2/products_form/ HTTP/1.1" 200 1075
"POST /hw2/products_form/ HTTP/1.1" 200 1075
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\forms.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hwproject\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2498
"GET /hw2/products_form/ HTTP/1.1" 200 1250
Internal Server Error: /hw2/products_form/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: table hw2app_productmodel has no column named image

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py", line 26, in products_form
    form.save()
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\forms\models.py", line 551, in save
    self.instance.save()
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\query.py", line 1845, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: table hw2app_productmodel has no column named image
"POST /hw2/products_form/ HTTP/1.1" 500 153986
Watching for file changes with StatReloader
Internal Server Error: /hw2/products_form/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: table hw2app_productmodel has no column named image

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py", line 26, in products_form
    form.save()
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\forms\models.py", line 551, in save
    self.instance.save()
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\query.py", line 1845, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: table hw2app_productmodel has no column named image
"POST /hw2/products_form/ HTTP/1.1" 500 154103
Internal Server Error: /hw2/products_form/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: table hw2app_productmodel has no column named image

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py", line 26, in products_form
    form.save()
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\forms\models.py", line 551, in save
    self.instance.save()
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\query.py", line 1845, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: table hw2app_productmodel has no column named image
"POST /hw2/products_form/ HTTP/1.1" 500 154103
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2498
"GET /hw2/products_form/ HTTP/1.1" 200 1241
"POST /hw2/products_form/ HTTP/1.1" 200 1283
Watching for file changes with StatReloader
"GET /hw2/products_form/ HTTP/1.1" 200 1241
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2498
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4158
"GET /static/admin/css/base.css HTTP/1.1" 200 21544
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2682
"GET /static/admin/css/login.css HTTP/1.1" 200 958
"GET /static/admin/css/responsive.css HTTP/1.1" 200 17905
"GET /static/admin/js/theme.js HTTP/1.1" 200 1943
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hwproject\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
Watching for file changes with StatReloader
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 5949
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 200 7131
"GET /admin/hw2app/clientmodel/ HTTP/1.1" 200 11051
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9042
"GET /static/admin/js/core.js HTTP/1.1" 200 6208
"GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
"GET /static/admin/js/actions.js HTTP/1.1" 200 8067
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6811
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /static/admin/js/filters.js HTTP/1.1" 200 978
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /admin/hw2app/productmodel/ HTTP/1.1" 200 12451
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/productmodel/add/ HTTP/1.1" 200 11693
"GET /static/admin/css/forms.css HTTP/1.1" 200 9090
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11800
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /static/admin/js/change_form.js HTTP/1.1" 200 606
"POST /admin/hw2app/productmodel/add/ HTTP/1.1" 302 0
"GET /admin/hw2app/productmodel/ HTTP/1.1" 200 13124
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hw2app/productmodel/ HTTP/1.1" 200 13184
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/productmodel/ HTTP/1.1" 200 13184
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 17283
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/22/change/ HTTP/1.1" 200 13848
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 17283
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/15/change/ HTTP/1.1" 200 13850
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 17283
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/productmodel/ HTTP/1.1" 200 13184
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hw2app/productmodel/ HTTP/1.1" 200 13747
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 17283
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 19026
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hw2app/productmodel/ HTTP/1.1" 200 13747
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 19026
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/clientmodel/ HTTP/1.1" 200 11553
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 19026
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 19026
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/clientmodel/ HTTP/1.1" 200 11553
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 19026
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/productmodel/ HTTP/1.1" 200 13747
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 19026
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/productmodel/ HTTP/1.1" 200 13747
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/productmodel/9/change/ HTTP/1.1" 200 12534
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 19026
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/clientmodel/ HTTP/1.1" 200 11553
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/productmodel/ HTTP/1.1" 200 13747
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 19026
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/productmodel/ HTTP/1.1" 200 13747
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hw2app/productmodel/ HTTP/1.1" 200 14051
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hw2app/productmodel/ HTTP/1.1" 200 14051
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 20013
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/?date_order__gte=2024-02-12&date_order__lt=2024-02-13 HTTP/1.1" 200 10520
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/? HTTP/1.1" 200 20013
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/?date_order__gte=2024-02-05&date_order__lt=2024-02-13 HTTP/1.1" 200 10520
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/?date_order__gte=2024-02-01&date_order__lt=2024-03-01 HTTP/1.1" 200 22117
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\models.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hw2app/ordermodel/?date_order__gte=2024-02-01&date_order__lt=2024-03-01 HTTP/1.1" 200 22727
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hw2app/ordermodel/?date_order__gte=2024-02-01&date_order__lt=2024-03-01 HTTP/1.1" 200 22727
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/productmodel/ HTTP/1.1" 200 14543
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /static/admin/img/search.svg HTTP/1.1" 200 458
"GET /admin/hw2app/productmodel/ HTTP/1.1" 200 14543
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/productmodel/?q=sofa HTTP/1.1" 200 11602
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hw2app/productmodel/?q=sofa HTTP/1.1" 200 11602
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/productmodel/?q=sofa HTTP/1.1" 200 11602
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/productmodel/?q= HTTP/1.1" 200 14809
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/clientmodel/ HTTP/1.1" 200 11553
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hw2app/clientmodel/ HTTP/1.1" 200 12045
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hw2app/clientmodel/ HTTP/1.1" 200 12045
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/clientmodel/ HTTP/1.1" 200 12045
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/clientmodel/add/ HTTP/1.1" 200 11368
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/clientmodel/ HTTP/1.1" 200 12045
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/clientmodel/ HTTP/1.1" 200 12045
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/clientmodel/add/ HTTP/1.1" 200 11368
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/clientmodel/ HTTP/1.1" 200 12045
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/clientmodel/4/change/ HTTP/1.1" 200 11721
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/clientmodel/ HTTP/1.1" 200 12045
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 20384
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/22/change/ HTTP/1.1" 200 13848
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 20384
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 23469
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\models.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 21789
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /admin/hw2app/ordermodel/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\options.py", line 714, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\options.py", line 1981, in changelist_view
    cl = self.get_changelist_instance(request)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\options.py", line 862, in get_changelist_instance
    return ChangeList(
           ^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\views\main.py", line 90, in __init__
    self.root_queryset = model_admin.get_queryset(request)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py", line 22, in get_queryset
    qs = qs.annotate(products_list=models.ExpressionWrapper(
                                   ^^^^^^
NameError: name 'models' is not defined
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 500 124304
"GET /admin/ HTTP/1.1" 200 8029
Internal Server Error: /admin/hw2app/ordermodel/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\options.py", line 714, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\options.py", line 1981, in changelist_view
    cl = self.get_changelist_instance(request)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\options.py", line 862, in get_changelist_instance
    return ChangeList(
           ^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\views\main.py", line 90, in __init__
    self.root_queryset = model_admin.get_queryset(request)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py", line 22, in get_queryset
    qs = qs.annotate(products_list=models.ExpressionWrapper(
                                   ^^^^^^
NameError: name 'models' is not defined
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 500 124139
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /admin/hw2app/ordermodel/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such function: array_agg

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\options.py", line 714, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\options.py", line 2120, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\query.py", line 1926, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such function: array_agg
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 500 179332
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /admin/hw2app/ordermodel/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\options.py", line 714, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\options.py", line 1981, in changelist_view
    cl = self.get_changelist_instance(request)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\options.py", line 862, in get_changelist_instance
    return ChangeList(
           ^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\views\main.py", line 90, in __init__
    self.root_queryset = model_admin.get_queryset(request)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py", line 23, in get_queryset
    qs = qs.annotate(products_list=models.ArrayAgg(
                                   ^^^^^^^^^^^^^^^
AttributeError: module 'django.db.models' has no attribute 'ArrayAgg'
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 500 124385
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /admin/hw2app/ordermodel/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\options.py", line 681, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'get_products_list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\utils.py", line 289, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\utils.py", line 322, in _get_non_gfk_field
    field = opts.get_field(name)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: OrderModel has no field named 'get_products_list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 343, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 319, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 310, in __init__
    super().__init__(*items)
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 217, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\contrib\admin\utils.py", line 298, in lookup_field
    value = attr(obj)
            ^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py", line 26, in get_products_list
    return obj.products_list
           ^^^^^^^^^^^^^^^^^
AttributeError: 'OrderModel' object has no attribute 'products_list'
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 500 387956
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 21789
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 21789
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 21789
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 21789
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 21789
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 21789
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 21789
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/productmodel/ HTTP/1.1" 200 14543
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/clientmodel/ HTTP/1.1" 200 12045
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 21789
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/productmodel/ HTTP/1.1" 200 14543
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 21789
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/add/ HTTP/1.1" 200 13601
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 21789
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/hw2app/ordermodel/ HTTP/1.1" 200 8981
"GET /static/admin/js/cancel.js HTTP/1.1" 200 884
"POST /admin/hw2app/ordermodel/ HTTP/1.1" 302 0
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 21040
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 20889
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
Watching for file changes with StatReloader
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 20889
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/clientmodel/ HTTP/1.1" 200 12045
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/productmodel/ HTTP/1.1" 200 14543
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/clientmodel/ HTTP/1.1" 200 12045
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 20889
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/productmodel/ HTTP/1.1" 200 14543
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/logout/ HTTP/1.1" 200 3817
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 8669
"GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
"GET /admin/hw2app/productmodel/ HTTP/1.1" 200 14543
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/ordermodel/ HTTP/1.1" 200 20889
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hw2app/clientmodel/ HTTP/1.1" 200 12045
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
